### ISSUE TITLE
uq是否无法在etcd上自建节点

### ISSUE THREAD

**Issue by sumory** [buaazp/uq#5]
使用以下方式启动uq：
![image](https://cloud.githubusercontent.com/assets/1326893/7388618/4098903c-ee99-11e4-9f5e-98e5e998a344.png)
查看etcd，无节点注册上来：
![image](https://cloud.githubusercontent.com/assets/1326893/7388640/6f2a2852-ee99-11e4-8217-a66f30c77ed9.png)

**Comment by buaazp** [comment]
etcd的参数需要是一个完整的URL：

```
http://localhost:4001
```

比如我启动的时候是这样：

```
./uq -etcd http://localhost:4001 -cluster uq
```

就能够注册上。

**Comment by sumory** [comment]
![image](https://cloud.githubusercontent.com/assets/1326893/7389129/a6796684-ee9d-11e4-9f62-b8769a5ebe1c.png)
果然，建议写在文档上，因为其他一些语言的库连接etcd时不需要加前缀的。

**Comment by buaazp** [comment]
好的～

**Comment by buaazp** [comment]
已修复，现在写不写`http://`都可以了。
